

$("#down1").click(function(){
$("#block1").toggle(900);
})
$("#down2").click(function(){
$("#block2").toggle(900);
})
$("#down3").click(function(){
$("#block3").toggle(900);
})
$("#down4").click(function(){
$("#block4").toggle(900);
})
$("#down5").click(function(){
$("#block5").toggle(900);
})
$("#down6").click(function(){
$("#block6").toggle(900);
})
$("#down7").click(function(){
$("#block7").toggle(900);
})
$("#down8").click(function(){
$("#block8").toggle(900);
})
$("#down9").click(function(){
$("#block9").toggle(900);
})
$("#down10").click(function(){
$("#block10").toggle(900);
})
$("#down11").click(function(){
$("#block11").toggle(900);
})
$("#down12").click(function(){
$("#block12").toggle(900);
})
$("#down13").click(function(){
$("#block13").toggle(900);
})